# Generated by Django 3.0.8 on 2022-11-12 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('is_premium', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='me', max_length=100)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('social_id', models.CharField(blank=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('following', models.ManyToManyField(related_name='follower', to='account.User')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
