# Generated by Django 3.0.8 on 2022-10-01 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='me', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_id',
            field=models.CharField(blank=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
