# Generated by Django 3.0.8 on 2022-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221001_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
    ]
