# Generated by Django 3.0.8 on 2022-10-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('privacy', models.CharField(choices=[('나만보기', '나만보기'), ('일부공개', '일부공개'), ('전체공개', '전체공개')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('temperature', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
