# Generated by Django 3.0.8 on 2022-10-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.TextField(default='  ', max_length=200),
            preserve_default=False,
        ),
    ]
