# Generated by Django 3.0.8 on 2022-10-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=15)),
                ('mood_temperature', models.IntegerField(default=25)),
                ('date', models.DateTimeField()),
                ('contents', models.TextField()),
                ('background_color', models.CharField(max_length=15)),
                ('private', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('webId', models.CharField(max_length=15, null=True)),
                ('webPw', models.CharField(max_length=25)),
                ('intro_text', models.TextField(null=True)),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('date', models.DateTimeField()),
                ('is_checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='user info')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='user info')),
                ('diary', models.ManyToManyField(to='api.Diary')),
                ('todo', models.ManyToManyField(to='api.Todo')),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_user', models.ManyToManyField(related_name='click_user', to='api.User')),
                ('target', models.ManyToManyField(related_name='target_user', to='api.User')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User', verbose_name='user info'),
        ),
    ]
