# Generated by Django 3.0.8 on 2022-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='public',
            field=models.CharField(choices=[('private', 'Private'), ('onlyFriends', 'Only Friends'), ('public', 'Public')], default='public', max_length=30),
        ),
    ]
