# Generated by Django 3.0.8 on 2022-10-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='diarylike',
            old_name='diary_id',
            new_name='diary',
        ),
        migrations.RenameField(
            model_name='diarylike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow_from_id',
            new_name='follow_from',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow_to_id',
            new_name='follow_to',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='goal_id',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='todolike',
            old_name='todo_id',
            new_name='todo',
        ),
        migrations.RenameField(
            model_name='todolike',
            old_name='user_id',
            new_name='user',
        ),
    ]
