# Generated by Django 3.0.8 on 2022-11-12 03:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 3, 33, 8, 654689, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 3, 33, 8, 654140, tzinfo=utc)),
        ),
    ]
