# Generated by Django 3.0.8 on 2022-10-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='color',
            field=models.CharField(blank=True, default='#FFF', max_length=20),
        ),
    ]
