# Generated by Django 3.0.8 on 2022-10-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='disclosure_choice',
            field=models.CharField(choices=[('onlyFriends', 'Only Friends'), ('public', 'Public'), ('private', 'Private')], default='public', max_length=30),
        ),
    ]
