# Generated by Django 3.0.8 on 2022-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='disclosure_choice',
            field=models.CharField(choices=[('public', 'Public'), ('onlyFriends', 'Only Friends'), ('private', 'Private')], default='public', max_length=30),
        ),
    ]
