# Generated by Django 3.0.8 on 2022-10-07 11:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221007_2022'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='disclosure_choice',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('onlyFriends', 'Only Friends')], default='public', max_length=30),
        ),
    ]
