# Generated by Django 3.0.8 on 2022-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221119_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='disclosure_choice',
            field=models.CharField(choices=[('onlyFriends', 'Only Friends'), ('private', 'Private'), ('public', 'Public')], default='public', max_length=30),
        ),
    ]
