# Generated by Django 3.0.8 on 2022-10-01 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221001_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likes',
            table='Likes',
        ),
    ]
