# Generated by Django 3.0.8 on 2022-10-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221001_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='check_likes_yn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='input_top_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_yn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_desc_yn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_yn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_sunday_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
