# Generated by Django 3.0.8 on 2022-11-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221119_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='todo',
            name='disclosure_choice',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('onlyFriends', 'Only Friends')], default='public', max_length=30),
        ),
    ]
