# Generated by Django 3.0.8 on 2022-11-19 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221119_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 14, 42, 23, 421349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 14, 42, 23, 413777, tzinfo=utc)),
        ),
    ]
