# Generated by Django 3.0.8 on 2022-11-19 15:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221119_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 15, 10, 9, 134245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 11, 19, 15, 10, 9, 126939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
