# Generated by Django 3.0.8 on 2022-10-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221001_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='followee',
            field=models.ForeignKey(db_column='followee', on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='follower',
            field=models.ForeignKey(db_column='follower', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='todogroup',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='group', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
