# Generated by Django 3.0.8 on 2022-10-01 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221001_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
