# Generated by Django 3.0.8 on 2022-10-01 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20221001_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoticon', models.ImageField(upload_to='')),
                ('diary_id', models.ForeignKey(db_column='diary_id', on_delete=django.db.models.deletion.CASCADE, related_name='diary_likes', to='api.Diary')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='diary_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DiaryLikes',
            },
        ),
        migrations.CreateModel(
            name='TodoLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoticon', models.ImageField(upload_to='')),
                ('todo_id', models.ForeignKey(db_column='todo_id', on_delete=django.db.models.deletion.CASCADE, related_name='todo_likes', to='api.TodoList')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='todo_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TodoLikes',
            },
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
