# Generated by Django 3.0.8 on 2022-11-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EasyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('days', models.ManyToManyField(to='todo.Days')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=20)),
                ('privacy', models.CharField(choices=[('숨기기', '숨기기'), ('나만보기', '나만보기'), ('일부공개', '일부공개'), ('전체공개', '전체공개')], default='나만보기', max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField()),
                ('is_done', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('time', models.TimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('easy_input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todo.EasyInput')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='TimeNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='Keep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('time', models.TimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Goal')),
            ],
        ),
        migrations.AddField(
            model_name='easyinput',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Goal'),
        ),
    ]
