# Generated by Django 3.0.8 on 2022-10-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_easy_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='easy_input',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todo.EasyInput'),
        ),
    ]
