# Generated by Django 3.0.8 on 2022-11-12 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        ('diary', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='todo.Todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryCheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='diary.Diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
