# Generated by Django 4.1.3 on 2022-11-19 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCheer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='todo.todo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryCheer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='diary.diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
