# Generated by Django 3.0.8 on 2022-10-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('diary', '0001_initial'),
        ('social', '0002_todocheer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryCheer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imoji', models.ImageField(upload_to='')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Diary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User')),
            ],
        ),
    ]
