# Generated by Django 3.0.8 on 2022-10-01 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        ('todo', '0001_initial'),
        ('social', '0003_diarycheer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycheer',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='diary.Diary'),
        ),
        migrations.AlterField(
            model_name='todocheer',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheer', to='todo.Todo'),
        ),
        migrations.DeleteModel(
            name='Following',
        ),
    ]
